import Head from 'next/head'
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAnglesRight, faAnglesLeft } from '@fortawesome/free-solid-svg-icons';

export default function Home() {
  return (
    <div className="flex justify-between items-center h-full w-screen">
      <Head>
        <title>Donovan Triplett</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/contact"><a><FontAwesomeIcon className="ml-5" icon={faAnglesLeft} style={{ fontSize: 35 }}></FontAwesomeIcon></a></Link>

      <main className="text-center font-mono">
        <p className="text-2xl">Donovan Triplett</p>
        <p>Web Developer</p>
      </main>

      <Link href="/about"><a><FontAwesomeIcon className='mr-5' icon={faAnglesRight} style={{ fontSize: 35 }}></FontAwesomeIcon></a></Link>
    </div>
  )
}
